### PR TITLE
Recursive Fix #187 & #174

### LINKED ISSUE #187: Error when trying to forecast on subsample of the data with recursive model
Hi Matt,

I get an error if I try to forecast on subsample of the data with recursive model.

```
# Packages
library(tidymodels)
library(modeltime)
library(timetk)


# Lag function for recursive forecasting
lag_function <- function(data) {
    data %>% 
        arrange(id, Date) %>% 
        group_by(id) %>% 
        tk_augment_lags(Weekly_Sales, .lags = 1:12) %>% 
        ungroup()
        
}


# Data preparation
data_tbl <- timetk::walmart_sales_weekly %>% 
    select(id, Date, Dept, Weekly_Sales) %>% 
    lag_function()

splits <- timetk::time_series_split(data = data_tbl, date_var = Date, assess = 12, cumulative = TRUE)


# Build model
recipe_spec <- recipe(Weekly_Sales ~ ., data = training(splits)) %>% 
    step_rm(Date) %>% 
    step_dummy(all_nominal_predictors()) %>% 
    step_zv(all_predictors())


model_spec <- boost_tree(mode = "regression", engine = "xgboost")

# Recursive model
recursive_model <- workflow() %>% 
    add_recipe(recipe_spec) %>% 
    add_model(model_spec) %>% 
    fit(training(splits)) %>% 
    modeltime::recursive(
        id = "id",
        transform = lag_function,
        train_tail = panel_tail(training(splits), id, 12)
    ) %>% 
    modeltime_table()

# Non-recursive model
non_recursive_model <- workflow() %>% 
    add_recipe(recipe_spec) %>% 
    add_model(model_spec) %>% 
    fit(training(splits)) %>% 
    modeltime_table()




# Non recursive model
fc_tbl <- non_recursive_model %>% 
    modeltime_forecast(
        new_data = testing(splits) %>% filter(!id == "1_1"),
        actual_data = splits$data %>% filter(!id == "1_1"),
        keep_data = TRUE
    )


# Recursive model
fc_tbl <- recursive_model %>% 
    modeltime_forecast(
        new_data = testing(splits) %>% filter(!id == "1_1"),
        actual_data = splits$data %>% filter(!id == "1_1"),
        keep_data = TRUE
    )
```
Error: Assigned data `pred_fun(...)` must be compatible with row subscript `new_data$rowid.. == i`.
✖ 6 rows must be assigned.
✖ Assigned data has 7 rows.
ℹ Only vectors of size 1 are recycled.
Error in `dplyr::filter()`:
! Problem while computing `..1 = .model_desc == "ACTUAL" | .key == "prediction"`.
Caused by error:
! object '.key' not found
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unknown or uninitialised column: `.key`.

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi @mdancho84,

I have created a PR to resolve some of the open issues related to recursive models. Basically I have applied a condition that when in the test dataset there are more levels in the id than in the stored train_tail, then this object is filtered with the same levels available in the test dataset.

Anything we discuss.

Regards,

### CODE REVIEW

**Comment by mdancho84** [comment]
Awesome!! I appreciate the help. Let me take a look over the next day or so and I'll provide any comments.

**Comment by AlbertoAlmuinha** [comment]
I just added a new commit to give a solution to the request #160 creating the function `drop_modeltime_model`.

Regards,

**Review by mdancho84 — APPROVED** [review]
I reviewed and am OK. Things we might need to plan for:
- The detect_net() I like this. But one thing I'm thinking is that if a model is not a glmnet style but has a class of "something_net", then it will get selected and might go through the glmnet prediction.

**Comment by AlbertoAlmuinha** [comment]
I thought the same yesterday, maybe it would be a better idea to look for the parsnip model classes with glmnet engines and encapsulate them under that function so there can be no confusion…

I'll take a look at it later

**Pull request merged**
