### PR TITLE
Theta Method

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi @mdancho84 ,

Here is the THETA method as requested in #93 . I think all should be ok after the CROSTON comments.

Regards,

### CODE REVIEW

**Comment by mdancho84** [comment]
Hey @AlbertoAlmuinha , 
Thanks for pulling this together. 

- The Theta Method changes look good. All tests pass. I can merge this part of the PR. 
- The Parallel Refit has a minor issue that is [breaking tests](https://github.com/business-science/modeltime/runs/2319693689?check_suite_focus=true). 

Here's what I'm seeing:
image

You should be able to fix this failure by adding `doParallel` to the list of imports. 

Also, before you resubmit, I'd run the test locally on your machine to make sure that `modeltime` passes R CMD. It's easy to do. Just go to the "Build" pane and click "Check".

image

**Comment by mdancho84** [comment]
If it becomes too complicated to fix issues with Parallel Processing, then we may want to split up and just tackle Theta method now.

**Review by mdancho84 — APPROVED** [review]

**Comment by AlbertoAlmuinha** [comment]
Hey @mdancho84 ,

To be honest, I didn't realize that committing directly included that commit in the PR you had already done!

I have fixed the vignetta problem since I have changed the cores to default to 1 (i.e. no parallelization by default). I think this is the most appropriate. If you want, pass modeltime_refit to a new branch so that we can test the times before putting it in master. Also think about the default configurations and this kind of things. The function should be working fine, but there are still some things to think about.

Also, we have to see which packages are really necessary to send to the workers (for the moment I have put those that allowed me to execute the example of getting_started_with_modeltime, but it could be that some more are necessary, or not).


Regards,

**Comment by mdancho84** [comment]
Nice work on the Theta method. Looks great. I'll take a look at the parallel processing next.

**Pull request merged**
