### PR TITLE
modeltime_residuals_tests

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi Matt,

I have created the modeltime_residuals_tests function to obtain the p-values ​​of the following statistical tests: Shapiro-Wilk, Box-Pierce, Ljung-Box and Durbin-Watson.  An is_residuals() function has been created to control the suitability of the input table to the function.  You can also find the corresponding tests with the testthat package.

Any issue you can tell me!

Regards!

### CODE REVIEW

**Comment by mdancho84** [comment]
Hey, I took a quick look, and the only issue that I'm wanting to avoid is the `car` dependency. 

It's only used for the `car::durbinWatsonTest()` function, so maybe we can recreate it or include some messaging if `car` is not installed. [Here is the code](https://github.com/cran/car/blob/master/R/durbinWatsonTest.R) for the function. 

What do you think?

**Comment by mdancho84** [comment]
It looks like a relatively simple test to make. 

```
d = sum((SARIMA111$residuals - lag(SARIMA111$residuals))^2, na.rm = TRUE) /
       sum(SARIMA111$residuals^2, na.rm = TRUE)
```

https://stats.stackexchange.com/questions/38187/durbin-watson-test-for-residuals-of-sarima1-1-1-in-r

**Comment by mdancho84** [comment]
Hey I've merged - I'll be tackling some changes to remove the dependency on the `car` package.

**Comment by AlbertoAlmuinha** [comment]
Great @mdancho84. I have also seen a useless “quiet” parameter in modeltime_residuals_tests function (so take it away or add a purr safely function to give it some sense).

**Comment by mdancho84** [comment]
OK, I've removed the `quiet` parameter. I've released changes in the development version. It's now named `modeltime_residuals_test()` and it has revised parameters and removed the `car` dependency. All good.

**Pull request merged**
