### PR TITLE
Recursive_Panel Function: First Version

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi @mdancho84 ,

I have developed a first version of the recursive_panel() function as requested in #67 .

Some details to keep in mind:

- The function has not been tested when the input is a workflow (so a little caution in this regard).

- When the input is a model_fit the function has been tested on the dataset shown as an example in the function documentation. The loop has been tested manually to check that the results are correct up to j = 5 and it seems to be working correctly.

If you have any comments, you know where to reach me.

Regards,

### CODE REVIEW

**Comment by mdancho84** [comment]
This looks cool!! I'll give it a review this weekend.

**Comment by mdancho84** [comment]
Hey, I've created a branch called "recursive_panel" since this is a bigger change and I don't want it breaking things until we get everything sorted.

**Comment by mdancho84** [comment]
You should be able to do a git-pull and switch your branch to recursive panel. 
image

**Comment by AlbertoAlmuinha** [comment]
Done @mdancho84 , I switched my branch to recursive_panel branch.

**Comment by mdancho84** [comment]
OK - great first round! I have a few comments and ideas. 

## Project 1

Refitting needs to be able to perform `panel_tail()`. So I want you to come up with a way to store the "id" feature so we can know how to use `panel_tail()` inside of the `modeltime_refit()`

image

## Project 2

Next, because `recursive()` and `recursive_panel()` are very similar, could we combine them using method dispatch? 

I'm thinking if we add a parameter called "id" to recursive setting it to NULL by default, we will know when the user adds an "id" that it's a panel forecast. 

Alternatively, we could just add an "id" parameter to `recursive_panel()` and this will help solve Problem 1. 

Let me know your thoughts.

**Comment by AlbertoAlmuinha** [comment]
Hi @mdancho84 ,

I think project 2 is a good idea and makes sense since as you rightly say, both functions are very similar. I will give it a thought to see how to unify them by method dispatch and try to solve at the same time the problem 1, that is to say, to store somehow the ID to use it later in modeltime_refit().

**Pull request merged**
