### PR TITLE
Upkeep

### PR DESCRIPTION
**Pull request by olivroy**
First part

* Remove docs dir
* Remove testthat:: as testthat is always loaded when testing (testthat also loads when you call load_all()
* remove library(modeltime) from examples
* Update GH actions
* Remove .DS_Store and adding to gitignore
* Remove roxygen2 and covr from Suggests

### CODE REVIEW

**Comment by olivroy** [comment]
@mdancho84 CI passing except for a vignette.

  Quitting from lines 62-63 [unnamed-chunk-3] (modeltime-spark.Rmd)
  Error: processing vignette 'modeltime-spark.Rmd' failed with diagnostics:
  ignoring SIGPIPE signal
  --- failed re-building ‘modeltime-spark.Rmd’

I can investigate in the follow-up PR where I will also fix the deprecation warnings from tidyverse and tidymodels and remove deps on tidyverse and tidymodels.

**Comment by mdancho84** [comment]
Java and Spark are added in the R-CMD-check and pkgdown.yaml

They are needed for the Spark vignette.

**Comment by mdancho84** [comment]
I'm rerunning. It's odd that only the ubuntu-latest release is failing.

**Comment by olivroy** [comment]
Also getting a warning that the java and python actions are deprecated. Using a more recent version.

Should a recent version of Spark be used too? 3.1.2 is two years old

**Comment by mdancho84** [comment]
I reran the failed test, and it's working fine. For whatever reason every once in a while we'll get a false negative with a test failure.

**Comment by olivroy** [comment]
Indeed. And the run with updated actions is on track to succeed.

**Pull request merged**
