### PR TITLE
Recursive panel

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi @mdancho84 ,

I have unified `recursive_panel()` and `recursive()` into a single function as discussed in #72 . I have also stored the id in object$spec$id so that it can be used in modeltime_refit().

Some tasks that remain to be performed:

- It is necessary to update the function examples to include recursive for panel_data.

- The workflows interface has not yet been tested (there shouldn't be problem but it needs to be checked).

Regards,

### CODE REVIEW

**Comment by mdancho84** [comment]
Excellent! Let me review tonight and I'll have feedback tomorrow. Nice work!😀

**Comment by mdancho84** [comment]
This is complete. I've successfully tested:
- Recursive Parsnip Model Fit
- Recursive Workflows
- Refitting Recursive Parsnip & Workflows

We will standardize on the Transform Function method. This is consistently implemented in both Standard and Panel Recursive Models.

**Comment by mdancho84** [comment]
I've just merged the changes to master.

**Comment by AlbertoAlmuinha** [comment]
Great @mdancho84

**Pull request closed without merging**
