### PR TITLE
New Metric Addition: MAAPE

### PR DESCRIPTION
**Pull request by AlbertoAlmuinha**
Hi @mdancho84 ,

I have included a new metric suitable for intermittent time series (MAAPE) as we discussed in a thread in the Slack community.

I have implemented this metric as suggested by Justin as a custom Yardstick metric and calling an already developed function of the TSrepr package.

On the other hand, the control has also been added in `modeltime_accuracy` so that when the MAPE value is infinite (intermittent series normally) the MAPE metric is exchanged for the MAAPE metric, thus keeping constant the number of metrics returned by the function.

Here is an example for a series returning the normal result and an intermittent series:

```
library(timetk)
library(tidymodels)
library(tidyverse)
library(lubridate)
library(modeltime)
library(rsample)

m4_monthly <- m4_monthly %>% filter(id == "M750")

splits1 <- initial_time_split(m4_monthly)

model_1 <- arima_reg() %>% set_engine("auto_arima") %>% fit(value ~ ., data = training(splits1))

#As before
modeltime_table(model_1) %>%
  modeltime_calibrate(testing(splits1)) %>%
  modeltime_accuracy()


foo <- structure(list(Week = structure(c(17054, 17061, 17068, 17075, 
                                         17082, 17089, 17096, 17103, 17110, 17117, 17124, 17131, 17138, 
                                         17145, 17152, 17159, 17166, 17173, 17180, 17187, 17201, 17208, 
                                         17215, 17222, 17229, 17236, 17243, 17250, 17257, 17264, 17271, 
                                         17278, 17285, 17292, 17299, 17306, 17313, 17320, 17327, 17334, 
                                         17341, 17348, 17355, 17362, 17369, 17376, 17383, 17390, 17397, 
                                         17404, 17411, 17418, 17425, 17432, 17439, 17446, 17453, 17460, 
                                         17467, 17474, 17481, 17488, 17495, 17502, 17509, 17516, 17523, 
                                         17530, 17537, 17544, 17551, 17558, 17565, 17572, 17579, 17586, 
                                         17593, 17600, 17607, 17614, 17621, 17628, 17635, 17642, 17649, 
                                         17656, 17663, 17670, 17677, 17684, 17691, 17698, 17705, 17712, 
                                         17719, 17726, 17733, 17740, 17747, 17754, 17761, 17768, 17775
), class = "Date"), Value = c(2L, 1L, 0L, 4L, 0L, 0L, 2L, 1L, 
                              1L, 0L, 0L, 2L, 1L, 2L, 0L, 1L, 1L, 0L, 2L, 0L, 1L, 3L, 3L, 0L, 
                              2L, 0L, 3L, 1L, 3L, 0L, 2L, 2L, 0L, 2L, 3L, 3L, 5L, 0L, 2L, 1L, 
                              0L, 3L, 1L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 4L, 0L, 0L, 1L, 3L, 0L, 
                              0L, 1L, 2L, 0L, 1L, 0L, 2L, 2L, 1L, 2L, 0L, 1L, 0L, 3L, 2L, 2L, 
                              2L, 1L, 1L, 2L, 2L, 3L, 4L, 3L, 2L, 1L, 0L, 3L, 1L, 1L, 3L, 0L, 
                              1L, 0L, 1L, 2L, 0L, 1L, 4L, 3L, 1L, 2L, 1L, 3L, 0L, 0L, 2L)), 
row.names = c(NA, -103L), class = "data.frame") %>% as_tibble()

foo %>% plot_time_series(.date_var = Week, .value = Value, .smooth = FALSE)

splits2 <- initial_time_split(foo)

model_2 <- arima_reg() %>% set_engine("auto_arima") %>% fit(Value ~ ., data = training(splits2))

#NEW
modeltime_table(model_2) %>%
  modeltime_calibrate(testing(splits2)) %>%
  modeltime_accuracy()
```

### CODE REVIEW

**Comment by mdancho84** [comment]
This is cool. A couple of comments:

- I'd like to keep the `default_forecast_accuracy_metric_set()` as-is since this is what I teach in the course and can be the minimal accuracy metrics.
- Some checks are failing indicating that the changes are causing downstream issues
- I'd like to add an expanded metric set that includes more metrics like the one you are proposing. We can add new metrics to this set. We can call it `expanded_forecast_accuracy_metric_set()` and add new and experimental accuracies as we see fit.

**Comment by AlbertoAlmuinha** [comment]
Hey,

Yes, I saw that everything was working and did the PR directly without doing the checks...let me check to see what it is all about.

Ok, can we create a second default by changing MAPE to MAAPE and call it for example when MAPE is infinite? What do you think?

**Comment by mdancho84** [comment]
I think we just add the `maape` as a new metric probably next to `mape` inside a new function `extended_forecast_accuracy_metric_set()`. 

When MAPE is NA, we should probably just leave it. The user can then use MAAPE. I'd rather leave it to the user to decide which to use.

**Comment by AlbertoAlmuinha** [comment]
The reason for making the change from `MAPE` to `MAAPE` was also to keep the number of metrics fixed in order to be able to develop DEA, which I believe is what would really bring more value to the end user once developed. If `MAPE` is infinite, my opinion is that we should change it to `MAAPE` keeping the rest of the metrics and we could print a message to inform the user of this...(after all...what does a metric with infinite value bring you?).

In addition, this change would only occur on certain occasions, and it is normal to continue printing everything as before...

**Comment by mdancho84** [comment]
OK, put your proposal together.

**Comment by AlbertoAlmuinha** [comment]
Hi @mdancho84 ,

I have finished making my changes, I think hopefully everything should be ok now. In the end I have thought about it and I have opted for the option you mentioned (create an additional set of metrics and in the case of detecting any intermittent series apply this set of metrics with MAAPE instead of the default and printing a message to inform the user).

My change of opinion is due to the fact that making the substitution was not so trivial when using the ID argument. We will be able to handle substitution on the other hand for global level when doing DEA development in my opinion.

Regards,

**Comment by mdancho84** [comment]
Excellent. I will do a review and let you know if I find anything, but I believe we are on the same page. 

Also, what are the next steps for the DEA implementation? Did you and Justin K talk about setting up a project?

**Comment by AlbertoAlmuinha** [comment]
We do not comment further on the implementation of DEA at this time. Yesterday I was looking and I saw that the authors of the benchmark package in R also have a book called "Benchmarking with DEA, SFA, and R" so I think it could be good to use that package since there are examples of use in the book.

**Comment by mdancho84** [comment]
Hey I'm trying to figure out what's going on with the tests, but got to run - vacation stuff. Let me know if you can figure out where the issues are here.

**Comment by AlbertoAlmuinha** [comment]
Hi @mdancho84 ,

I've been having a look at this and the problem was that the nested test was not taking into account the maape metric in the column count and therefore an extra column had to be added in a couple of places.

Now in principle it should be ok.

**Comment by mdancho84** [comment]
Ah, OK. Let me take a look.

**Comment by AlbertoAlmuinha** [comment]
Matt, could we take a look at this?

The longer we wait, the more difficult it becomes to join the main branch because conflicts arise. I understand that this is not at all a priority but it should not take long. Tell me what you think, right now this branch has a conflict in the NAMESPACE file.

**Comment by mdancho84** [comment]
Ok, I agree. I have two comments:

1. We should not make any changes to the default accuracy metric set. I think we leave this as-is. We can add a warning message if MAPE is Inf indicating to use the extended metric set. 

2. We should move the additional dependency for the new functionality to suggests, which will prevent our package from failing if anything happens to it. This is more of a maintenance concern that we can avoid getting kicked off CRAN because of it.

**Comment by AlbertoAlmuinha** [comment]
Perfect Matt, I can make those changes!

**Comment by AlbertoAlmuinha** [comment]
I'm closing this, don't know what happened with my git branch :S

**Pull request closed without merging**
